User: !include User.raml
UserArray: !include UserArray.raml
UserProfile: !include UserProfile.raml
UserRole: !include UserRole.raml
UserRoleArray: !include UserRoleArray.raml
Error: !include Error.raml
