displayName: Users
description: Work with `User` objects.
get:
    description: List of `Users` objects.
    queryParameters:
        customerId:
            type: string
            required: false
            description: Output only user objects that have the passed customer assigned.
            example: customerId=abc
        supplierId:
            type: string
            required: false
            description: Output only user objects that have the passed supplier assigned.
            example: supplierId=abc
        ids:
            type: string|array
            required: false
            description: Limits the output to the passed user IDs.
            example: ids=ocadmin,svc_supplier,svc_auth
            example: ids[]=ocadmin&ids[]=svc_supplier&ids[]=svc_auth
        include:
            type: string
            description: Additional, comma separated user properties to include.
            example: include=user,profile
    responses:
        200:
            body:
                application/json:
                    type: UserArray
post:
    description: Creates a new user.
    is:
        - sendConflict
        - sendGeneralError
    body:
        application/json:
            type: User
    responses:
        202:
            body:
                application/json:
                    type: User
/{id}:
    uriParameters:
        id:
            type: string
            description: Unique identifier of a user.
        include:
            type: string
            description: Additional, comma separated user properties to include.
            example: include=user,profile
    get:
        description: Returns a single `User` object.
        is:
            - sendNotFound
        queryParameters:
            include:
                type: string
                required: false
                description: Endpoint will return the included comma seperated models
                example: include=profile
        responses:
          200:
            body:
                application/json:
                    type: User

    put:
        description: Updates a user but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        responses:
            202:
                body:
                    application/json:
                        type: User

/current:
    get:
        description: Returns a single `User` object for the user currently logged in.
        is:
            - sendNotFound
        responses:
          200:
            body:
                application/json:
                    type: User

    put:
        description: Updates the user currently logged in but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        responses:
            202:
                body:
                    application/json:
                        type: User

/{id}/profile:
    uriParameters:
        id:
            type: string
            description: Unique identifier of a user.
            pattern: \w{3}
    get:
        description: Resturns a single user's profile.
        is:
            - sendNotFound
        responses:
          200:
            body:
                application/json:
                    type: UserProfile
    put:
        description: Updates a user's profile but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        responses:
            202:
                body:
                    application/json:
                        type: UserProfile

/current/profile:
    get:
        description: Returns the profile of the user currently logged in.
        is:
            - sendNotFound
        responses:
          200:
            body:
                application/json:
                    type: UserProfile
    put:
        description: Updates the profile of the user currently logged in but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        responses:
            202:
                body:
                    application/json:
                        type: UserProfile

/{id}/assignableRoles:
    uriParameters:
        id:
            type: string
            description: Unique identifier of a user.
            pattern: \w{3}
    get:
        description: Returns list of roles which currently logged user can assign to given user.
        is:
            - sendNotFound
            - sendGeneralError
        responses:
          200:
            body:
                application/json:
                    type: array
                    example: |
                        ["supplier", "user"]

/current/assignableRoles:
    get:
        description: Returns list of roles current user can assign to himself.
        is:
            - sendNotFound
            - sendGeneralError
        responses:
          200:
            body:
                application/json:
                    type: array
                    example: |
                        ["supplier", "user"]

/{userId}/roles/{roleId}:
    uriParameters:
        userId:
            type: string
            description: Unique identifier of a user.
            pattern: \w{3}
        roleId:
            type: string
            description: Unique identifier of a role.
            pattern: \w{3}

    put:
        description: Adds the role with roleId to the the user with userId.
        is:
            - sendNotFound
            - sendGeneralError
            - sendForbidden
        responses:
            201:
                body:
                    application/json:
                        type: array
                        example: |
                            ["admin", "xtenant"]

    delete:
        description: Removes role from given user.
        is:
            - sendNotFound
            - sendGeneralError
            - sendForbidden
        responses:
            201:
                body:
                    application/json:
                        type: array
                        example: |
                            ["admin", "xtenant"]
