displayName: Users
description: Work with `User` objects.
get:
    description: List of `Users` objects.
    queryParameters:
        customerId:
            type: string
            required: false
            description: Output only user objects that have the passed customer assigned.
            example: customerId=abc
        supplierId:
            type: string
            required: false
            description: Output only user objects that have the passed supplier assigned.
            example: supplierId=abc
    responses:
        200:
            body:
                application/json:
                    type: UserArray
post:
    description: Creates a new user.
    is:
        - sendConflict
        - sendGeneralError
    body:
        application/json:
            type: User
    responses:
        202:
            body:
                application/json:
                    type: User
/{id}:
    uriParameters:
        id:
            type: string
            description: Unique identifier of a user.
    get:
        description: Returns a single `User` object.
        is:
            - sendNotFound
        queryParameters:
            include:
                type: string
                required: false
                description: Endpoint will return the included comma seperated models
                example: include=profile
        responses:
          200:
            body:
                application/json:
                    type: User

    put:
        description: Updates a user but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        queryParameters:
            tokenUpdate:
                type: string
                required: false
                description: Forces the service to synchronously updated cached user tokens.
                example: tokeUpdate=true
        responses:
            202:
                body:
                    application/json:
                        type: User

/current:
    get:
        description: Returns a single `User` object for the user currently logged in.
        is:
            - sendNotFound
        responses:
          200:
            body:
                application/json:
                    type: User

    put:
        description: Updates the user currently logged in but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        queryParameters:
            tokenUpdate:
                type: string
                required: false
                description: Forces the service to synchronously updated cached user tokens.
                example: tokeUpdate=true
        responses:
            202:
                body:
                    application/json:
                        type: User

/{id}/profile:
    uriParameters:
        id:
            type: string
            description: Unique identifier of a user.
            pattern: \w{3}
    get:
        description: Resturns a single user's profile.
        is:
            - sendNotFound
        responses:
          200:
            body:
                application/json:
                    type: UserProfile
    put:
        description: Updates a user's profile but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        queryParameters:
            tokenUpdate:
                type: string
                required: false
                description: Forces the service to synchronously updated cached user tokens.
                example: tokeUpdate=true
        responses:
            202:
                body:
                    application/json:
                        type: UserProfile

/current/profile:
    get:
        description: Returns the profile of the user currently logged in.
        is:
            - sendNotFound
        responses:
          200:
            body:
                application/json:
                    type: UserProfile
    put:
        description: Updates the profile of the user currently logged in but changes only the values passed.
        is:
            - sendNotFound
            - sendGeneralError
            - sendFailedDependency
        queryParameters:
            tokenUpdate:
                type: string
                required: false
                description: Forces the service to synchronously updated cached user tokens.
                example: tokeUpdate=true
        responses:
            202:
                body:
                    application/json:
                        type: UserProfile
